version: 2.0
jobs:
  build:
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/agonzalezro/botella
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install glide and install dependencies
          command: | 
            curl https://glide.sh/get | sh
            glide install
      - run:
          name: Run tests
          command: go test $(glide novendor)